[package]
name = "node_tree"
version = "0.1.0"
edition = "2021"
rust-version = "1.78"

exclude = [
    ".github/*",
    ".vscode/*",
    "tests/*",
]

keywords    = ["framework", "utility", "gamedev"]
repository  = "https://github.com/LunaticWyrm467/node_tree"
description = """
A specialized crate that allows to create an extendable system for use for games or large programs.
This system is made up of autonomous execution agents known as Nodes, which have their own data and can communicate to other nodes.
Inspired by Godot!
"""
license = "MIT OR Apache-2.0"

[dependencies]
node_tree_derive = { path = "../node_tree_derive" }
